---
title: "Corona Virus Report"
author:
- familyname: Xinying
  othernames: Xu
  address: Monash Universtidy
  email: xxuu0075@student.monash.edu
  correspondingauthor: true
  qualifications:  students in Monash university
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```

\section*{Country China and United_Kingdom"}
```{r table}
world <- read.csv("Data/worldwidecases.csv")
covid19 <- world %>%
  filter(countriesAndTerritories %in% c("China","United_Kingdom"))%>%
  select(dateRep, day, month, year, cases, deaths, popData2018,countriesAndTerritories, )%>%
  rename(country = "countriesAndTerritories") %>%
  group_by(country)%>%
  summarise(total_death = sum(deaths),
            total_cases = sum(cases))
knitr::kable(covid19,
             caption = "The information of China and UK")
```

In table \@ref(tab:table), we can know about the total cases and total deaths of the two countries.

```{r fig}
ggplot(covid19,
       aes(country,total_death,
           fill = country)) +
  geom_col()
```

In the figure \@ref(fig:fig), it shows the figure of total deaths in the two countries.

more information, please check @covid2020modeling



